apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anthos-sds-leader-election-role
  namespace: sds-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anthos-sds-leader-election-rolebinding
  namespace: sds-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anthos-sds-leader-election-role
subjects:
- kind: ServiceAccount
  name: anthos-sds-controller-manager
  namespace: sds-system

---
