apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: anthos-sds-manager-role
rules:
- apiGroups:
  - anthos-sds.anthos.io
  resources:
  - sds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anthos-sds.anthos.io
  resources:
  - sds/finalizers
  verbs:
  - update
- apiGroups:
  - anthos-sds.anthos.io
  resources:
  - sds/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anthos-sds-robin-clusterrole-creator
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  - nodes
  - nodes/stats
  - nodes/proxy
  - pods
  - storageclasses
  - persistentvolumes
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - volumeattachments
  - volumeattachments/status
  - volumesnapshotclasses
  - volumesnapshots
  - volumesnapshots/status
  - volumesnapshotcontents
  - volumesnapshotcontents/status
  - namespaces
  - events
  - configmaps
  - secrets
  - services
  - services/status
  - customresourcedefinitions
  - robinclusters
  - robinclusters/status
  - tokenreviews
  - subjectaccessreviews
  - endpoints
  - statefulsets
  - deployments
  - daemonsets
  - replicasets
  - rolebindings
  - clusterrolebindings
  - clusterroles
  - roles
  - jobs
  - serviceaccounts
  - certificatesigningrequests
  - certificatesigningrequests/approval
  - applications
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - kubernetes.io/legacy-unknown
  resources:
  - signers
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anthos-sds-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anthos-sds-manager-role
subjects:
- kind: ServiceAccount
  name: anthos-sds-controller-manager
  namespace: sds-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anthos-sds-robin-clusterrole-creator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anthos-sds-robin-clusterrole-creator
subjects:
- kind: ServiceAccount
  name: anthos-sds-controller-manager
  namespace: sds-system

---
